### ISSUE TITLE
Setting custom resolution doesn't work with some old Nvidia cards

### ISSUE THREAD

**Issue by breversa** [ProfessorKaos64/grub-customizer#2]
Hi!

Setting a custom resolution in _Display Settings > Custom resolution_ doesn't work with some old Nvida cards/chipsets, such as the `NVIDIA C61 [GeForce 6150SE nForce 430]`.

The reason seems to be that they expect `GRUB_GFXMODE` resolution to be `XXXXxYYYY-ZZ` (colour depth following a **dash**) instead of `XXXXxYYYYxZZ` (colour depth following an **x**).

Source:
https://wiki.archlinux.org/title/GRUB/Tips_and_tricks#Setting_the_framebuffer_resolution

Additional info:
```
$ inxi --system --graphics
System:
  Host: oem-System-Product-Name Kernel: 5.15.0-46-lowlatency x86_64 bits: 64
    Desktop: Xfce 4.16.0 Distro: Linux Mint 21 Vanessa
Graphics:
  Device-1: NVIDIA C61 [GeForce 6150SE nForce 430] driver: nouveau v: kernel
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: nouveau
    unloaded: fbdev,modesetting,vesa gpu: nouveau resolution: 1920x1080~60Hz
  OpenGL: renderer: NV4C v: 2.1 Mesa 22.0.5
```

**Comment by mdeguzis** [comment]
Sorry about this, I believe I imported this a long* time ago when working on SteamOS v1/v2 and it is no longer maintained.

**Comment by breversa** [comment]
I understand. So let's leave this here in case someone wonders why their resolution isn't applied, and/or wishes to fork this project.
